#!/usr/bin/env python3
"""Generate docs/framework-mappings.md from SKILL.md.

The per-rule mappings in SKILL.md are the source of truth. This script inverts
them into a framework-first index, so an auditor asking "which DSB rules cover
SSDF PW.4.1?" gets an answer without reading all 42 rules.

The output is generated, never hand-edited. tests/test_mappings.py fails if the
committed file drifts from what this script produces.

Usage:
    python tools/generate_mappings.py            # rewrite the file
    python tools/generate_mappings.py --check    # exit 1 if it would change
    python tools/generate_mappings.py --stdout   # print, write nothing
"""

import argparse
import pathlib
import re
import sys

# Importable both as a script and under pytest, which puts tools/ on the path.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from validate_skill import ROOT, SKILL, parse_rules  # noqa: E402

OUTPUT = ROOT / "docs" / "framework-mappings.md"

# Order matters: "OWASP SAMM" must be tested before the bare "OWASP " prefix,
# which is how OWASP CI/CD controls are written.
FRAMEWORKS = [
    ("ssdf", "SSDF ", "NIST SSDF", "Secure Software Development Framework (SP 800-218)"),
    ("slsa", "SLSA ", "SLSA", "Supply-chain Levels for Software Artifacts"),
    ("owasp_samm", "OWASP SAMM ", "OWASP SAMM", "Software Assurance Maturity Model"),
    ("owasp_cicd", "OWASP ", "OWASP CI/CD", "OWASP Top 10 CI/CD Security Risks"),
    ("cncf", "CNCF ", "CNCF", "CNCF Software Supply Chain Security guidance"),
]


def parse_mappings(line):
    """Split one rule's italic mappings line into {framework_key: [controls]}."""
    found = {key: [] for key, *_ in FRAMEWORKS}

    for part in (p.strip() for p in (line or "").split("·")):
        if not part or part.startswith("Curriculum:"):
            continue
        for key, prefix, *_ in FRAMEWORKS:
            if part.startswith(prefix):
                controls = part[len(prefix):]
                found[key].extend(c.strip() for c in controls.split(",") if c.strip())
                break

    return found


def sort_key(control):
    """Sort controls naturally: PW.4.1 before PW.8.1, CICD-SEC-2 before -10."""
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", control)]


def render(rules):
    parsed = [(r, parse_mappings(r["mappings"])) for r in rules]
    out = []

    out.append("# Framework Mappings")
    out.append("")
    out.append("<!-- Generated by tools/generate_mappings.py. Do not edit by hand. -->")
    out.append("")
    out.append(
        "Every DSB rule maps to recognized industry guidance. The mappings are "
        "authored\ninline in [`SKILL.md`](../SKILL.md) §3 and inverted here so a "
        "framework control can be\ntraced to the DSB rules that carry it."
    )
    out.append("")
    out.append("```text")
    out.append("Industry Standards / Best Practices")
    out.append("              ↓")
    out.append("DSB DevSecOps Engineering Methodology")
    out.append("              ↓")
    out.append("DSB Rules")
    out.append("              ↓")
    out.append("Organizational Context")
    out.append("              ↓")
    out.append("Platform / Tool Implementation")
    out.append("```")
    out.append("")
    out.append(
        "Frameworks **inform** the DSB methodology. They do not replace engineering\n"
        "judgment, and a mapping is not a claim of certification or full coverage of\n"
        "the referenced framework."
    )
    out.append("")

    # --- coverage summary -------------------------------------------------
    out.append("## Coverage")
    out.append("")
    out.append("| Framework | Controls referenced | DSB rules citing it |")
    out.append("|---|---|---|")
    for key, _prefix, label, _desc in FRAMEWORKS:
        controls = {c for _r, m in parsed for c in m[key]}
        citing = {r["id"] for r, m in parsed if m[key]}
        out.append(f"| {label} | {len(controls)} | {len(citing)} |")
    out.append("")

    # --- framework-first index -------------------------------------------
    for key, _prefix, label, desc in FRAMEWORKS:
        index = {}
        for rule, mapped in parsed:
            for control in mapped[key]:
                index.setdefault(control, []).append(rule["id"])
        if not index:
            continue

        out.append(f"## {label}")
        out.append("")
        out.append(f"{desc}.")
        out.append("")
        out.append("| Control | DSB rules |")
        out.append("|---|---|")
        for control in sorted(index, key=sort_key):
            ids = ", ".join(f"`{i}`" for i in sorted(set(index[control])))
            out.append(f"| `{control}` | {ids} |")
        out.append("")

    # --- rule-first index -------------------------------------------------
    out.append("## By DSB rule")
    out.append("")
    out.append("| Rule | Title | Frameworks |")
    out.append("|---|---|---|")
    for rule, mapped in parsed:
        cites = []
        for key, _prefix, label, _desc in FRAMEWORKS:
            if mapped[key]:
                cites.append(f"{label} {', '.join(mapped[key])}")
        out.append(f"| `{rule['id']}` | {rule['title']} | {'; '.join(cites) or '—'} |")
    out.append("")

    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate docs/framework-mappings.md from SKILL.md.",
        epilog="Example: python tools/generate_mappings.py --check",
    )
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file is out of date")
    parser.add_argument("--stdout", action="store_true",
                        help="print the result instead of writing it")
    args = parser.parse_args()

    content = render(parse_rules(SKILL.read_text()))

    if args.stdout:
        print(content, end="")
        return 0

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(f"FAIL: {OUTPUT.relative_to(ROOT)} is out of date — "
                  "run python tools/generate_mappings.py")
            return 1
        print(f"OK: {OUTPUT.relative_to(ROOT)} is current")
        return 0

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
